// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sekkgmahnapuwgxpywjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNla2tnbWFobmFwdXdneHB5d2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMjg2NzgsImV4cCI6MjA2MDYwNDY3OH0.9V2HavogevwI4340cYiU5BktmP7LoYV-zDe9B48vdS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);